### PR TITLE
Consecutive jumps

### PR DESCRIPTION
**Pull request by joeperpetua**
Initial draft for consecutive jumps #10
This is the game flow I went for, let me know if this is aligned with the vision for the game.

```mermaid
flowchart TD
    C{"Piece eaten?"} -- No --> D["Switch turn"]
    C -- Yes --> F["Piece promoted?"]
    A["Move piece"] --> C
    F -- Yes --> D
    F -- No --> n1["Can jump again?"]
    n1 -- No --> D
    n1 -- Yes --> n2["Keep turn"]

    F@{ shape: diam}
    n1@{ shape: decision}
    n2@{ shape: proc}
```

I created a test for a straight double jump, if the flow is the one desired, I will continue refining some details (specially about the boundary checks) and I will create the tests for the remaining cases.

### Update 29/11
Also added an internal function to calculate the landing position for a given jump. The algorithms replaced were not working well for king pieces as they depended on the position attribute of the piece to calculate the possible jumps.

### Update 30/11
This PR contains the following tests:
- test_piece41_double_jump_straight_piece05
- test_piece23_double_jump_zigzag_piece72
- test_king05_triple_jump_zigzag_piece23
- test_king72_quad_jump_zigzag_piece72

### CODE REVIEW

**Comment by bitfalt** [comment]
I would say the flow is correct. However, instead of keeping the turn it should eat the next possible piece. It is kind of forcing the move for the player.

**Comment by joeperpetua** [comment]
@bitfalt Thanks for the feedback!
What should we do if there are multiple possible jumps? 

I guess repeating the turn can be a good approach to handle all possible cases. We could also emit and event RepeatTurn or so in order for the client to handle it correctly and update the UI accordingly for the user to know he can keep eating pieces.

**Review by bitfalt — APPROVED** [review]
lgtm! The idea of not changing the turn looks good and I like the implementation. Good job, overall! :D

**Comment by joeperpetua** [comment]
Thanks for the comments, it's been great to contribute on the project!

**Pull request merged**
