### PR TITLE
feat: refactor models

### PR DESCRIPTION
**Pull request by coxmars**
### Description
This PR addresses the issue of improving the modular structure of the codebase by:

1. Migrating logic related to specific models into their respective traits.
2. Restructuring the `models` directory for better organization and readability.
3. Updating imports to reflect the new directory structure.

image

### CODE REVIEW

**Comment by gianalarcon** [comment]
Hi @coxmars Any updates on this PR?

**Comment by coxmars** [comment]
> Hi @coxmars Any updates on this PR?

I'm still working on it

**Comment by coxmars** [comment]
Hi @gianalarcon, I have already organized the models separately, updated the imports where needed and validated that everything worked correctly, is this what is needed or am I missing something else?

**Comment by Gianfranco99** [comment]
Hi gm! @coxmars 
The logic of the actions is missing, it must be migrated to the respective traits of each model, as shown in the example of the issue description , like this

```
#[generate_trait]

 impl PieceImpl of PieceTrait {
         fn new(
             session_id: u64,
             row: u8,
             col: u8,
             player: ContractAddress,
             position: Position,
         ) -> Piece {
                   Piece {
                       session_id,
                       row,
                       col,
                       player,
                       position,
                       is_king: false,
                       is_alive: true,
                   }
         }
     ```
     You can check this repo also , for more examples
     https://github.com/RuneLabsxyz/Octoguns/blob/main/contracts/src/models/sessions.cairo

**Review by Gianfranco99 — CHANGES_REQUESTED** [review]
Hi gm! @coxmars

The logic of the actions is missing, it must be migrated to the respective traits of each model, as shown in the example of the issue description , like this

```
#[generate_trait]

 impl PieceImpl of PieceTrait {
         fn new(
             session_id: u64,
             row: u8,
             col: u8,
             player: ContractAddress,
             position: Position,
         ) -> Piece {
                   Piece {
                       session_id,
                       row,
                       col,
                       player,
                       position,
                       is_king: false,
                       is_alive: true,
                   }
         }
```
    
     
     

You can check this repo also , for more examples 
https://github.com/RuneLabsxyz/Octoguns/blob/main/contracts/src/models/sessions.cairo

**Comment by coxmars** [comment]
> Hi gm! @coxmars
> 
> The logic of the actions is missing, it must be migrated to the respective traits of each model, as shown in the example of the issue description , like this
> 
> ```
> #[generate_trait]
> 
>  impl PieceImpl of PieceTrait {
>          fn new(
>              session_id: u64,
>              row: u8,
>              col: u8,
>              player: ContractAddress,
>              position: Position,
>          ) -> Piece {
>                    Piece {
>                        session_id,
>                        row,
>                        col,
>                        player,
>                        position,
>                        is_king: false,
>                        is_alive: true,
>                    }
>          }
> ```
> 
> You can check this repo also , for more examples https://github.com/RuneLabsxyz/Octoguns/blob/main/contracts/src/models/sessions.cairo

Thanks sir, I will do it asap in the next days 🫡

**Comment by gianalarcon** [comment]
Hi @coxmars Any updates on this PR?

**Pull request closed without merging**
