### PR TITLE
Bootstrap multiple jumps

### PR DESCRIPTION
**Pull request by saimeunt**
WIP: Multiple jumps

### CODE REVIEW

**Comment by gianalarcon** [comment]
Hi @saimeunt . Any updates on this, If you have some questions please let me knoe

**Comment by gianalarcon** [comment]
Hi @saimeunt . Have you faced any issue? If you busy on something else,  we will open the issue again for another candidate.

**Comment by saimeunt** [comment]
@gianalarcon hey I'm almost done I will finish it today.

**Comment by gianalarcon** [comment]
@saimeunt sorry Sir. The issue has been assigned to someone else. We close the PR for now. You can join us on next OD hack, Thanks!

**Comment by saimeunt** [comment]
@gianalarcon then at least show some respect for the work done and integrate my bugfix on `check_has_valid_moves` which at the moment will return false negatives by returning too early without checking for the other direction. You can't expect me to join for the next OD Hack if you just discard contributions without reviewing them.

Bug:
https://github.com/The-Marquis-Gaming/checkers-dojo/blob/main/dojo-starter/src/systems/actions.cairo#L374
https://github.com/The-Marquis-Gaming/checkers-dojo/blob/main/dojo-starter/src/systems/actions.cairo#L398

Fix:
https://github.com/saimeunt/checkers-dojo/blob/feat/mutiple-jumps/dojo-starter/src/systems/actions.cairo#L405-L440

**Pull request closed without merging**
