### PR TITLE
Feat/bump dojo 1.0.1

### LINKED ISSUE #6: Smart Contracts: Bump to dojo v1.0.1
## Issue Overview

1. Bump to dojo v1.0.1
2. Make sure all tests pass
3. Use new features of v1.0.1 as [world.write_models](https://github.com/dojoengine/dojo/blob/f6659db7cf081ac4071b2c2e9555fad0eed12210/crates/dojo/core-cairo-test/src/tests/world/storage.cairo#L33). Implement this new feature on [`initialize_player_pieces`](https://github.com/The-Marquis-Gaming/checkers-dojo/blob/7af812a08ea8048952766e55054e8ad999e82e92/dojo-starter/src/systems/actions.cairo#L238)
4. Improve tests to use `write_models` and `read_models`
5. Refactor `fn spawn()` to become internal function. It shouldn't be external function

### PR DESCRIPTION
**Pull request by joeperpetua**
Closes #6 

- Bump config files
- Update test namespace and contract definitions
- Add tests permissions sync
- Move `spaw()` into `InternalTrait`
- Delete old manifests
- Update docs to reflect latest Dojo tool chain version

All tests passing: 

image

### CODE REVIEW

**Comment by gianalarcon** [comment]
Hi @joeperpetua. The PR looks goods, thanks for your contributions. 

Just missing the point 3 and 4 from the issue description.

> *3. Use new features of v1.0.1 as [world.write_models](https://github.com/dojoengine/dojo/blob/f6659db7cf081ac4071b2c2e9555fad0eed12210/crates/dojo/core-cairo-test/src/tests/world/storage.cairo#L33). Implement this new feature on [`initialize_player_pieces`](https://github.com/The-Marquis-Gaming/checkers-dojo/blob/7af812a08ea8048952766e55054e8ad999e82e92/dojo-starter/src/systems/actions.cairo#L238)
> *4. Improve tests to use `write_models` and `read_models`

**Comment by joeperpetua** [comment]
> Hi @joeperpetua. The PR looks goods, thanks for your contributions.
> 
> Just missing the point 3 and 4 from the issue description.
> 
> > *3. Use new features of v1.0.1 as [world.write_models](https://github.com/dojoengine/dojo/blob/f6659db7cf081ac4071b2c2e9555fad0eed12210/crates/dojo/core-cairo-test/src/tests/world/storage.cairo#L33). Implement this new feature on [`initialize_player_pieces`](https://github.com/The-Marquis-Gaming/checkers-dojo/blob/7af812a08ea8048952766e55054e8ad999e82e92/dojo-starter/src/systems/actions.cairo#L238)
> > *4. Improve tests to use `write_models` and `read_models`

Thanks for the comments!

The `write_model` and `read_model` functions are already implemented, both in [actions.cairo](https://github.com/joeperpetua/checkers-dojo/blob/feat/bump-dojo-1.0.1/dojo-starter/src/systems/actions.cairo) and [test_world.cairo](https://github.com/joeperpetua/checkers-dojo/blob/feat/bump-dojo-1.0.1/dojo-starter/src/tests/test_world.cairo), aren't they?

If I am missing something, let me know!

**Comment by gianalarcon** [comment]
There is a [world.write_models](https://github.com/dojoengine/dojo/blob/f6659db7cf081ac4071b2c2e9555fad0eed12210/crates/dojo/core-cairo-test/src/tests/world/storage.cairo#L33) (with `s` an the end) for batch processing methods for writing.
Same for read_models

**Comment by joeperpetua** [comment]
> There is a [world.write_models](https://github.com/dojoengine/dojo/blob/f6659db7cf081ac4071b2c2e9555fad0eed12210/crates/dojo/core-cairo-test/src/tests/world/storage.cairo#L33) (with `s` an the end) for batch processing methods for writing.
> Same for read_models

My bad then, will get to it ASAP!

**Comment by joeperpetua** [comment]
GM @gianalarcon 

Done with the implementation for batch read/write. I also did it in `initialize_pieces_session_id` and `change_is_alive`.
I had to change some tests flow a little to be able to read the models in batches, but I did my best to keep it readable and coherent. 

Let me know if any change is needed!

Tests output: 

image

**Pull request merged**
